name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - foo/bar**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
